[package]
name = "try_2"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.24"
egui = "0.24"
rusqlite = { version = "0.30", features = ["bundled"] }
rand = "0.8"
image = "0.24"
simple_excel_writer = "0.2"
